config/routes.rb
Rails.application.routes.draw do

root 'home#index'
resources :users, only: [:create, :update, :show, :edit]

get 'register', to: 'users#new'
 
get '/login', to: 'sessions#new'
post '/login', to: 'sessions#create'
get '/logout', to: 'sessions#destroy'
get 'top_stories', to: 'home#top_stories' 
get 'articles', to: 'home#articles'
get 'networking', to: 'home#networking'
get 'events', to: 'home#events'

end

app/models/user.rb
class User < ActiveRecord::Base
  
  validates :username, presence: true, uniqueness: true
  validates :password, presence: true, on: :create, length: {minimum: 5}
  validates :zipcode, presence: true, on: :create, length: {minimum: 5} 
  validates :interest1, :city, :state, :free_time, presence: true, on: :create
  has_secure_password validations: false

  before_save :generate_slug

  def generate_slug 
    str = self.username
    str = str.strip
    str.gsub! /\s*[^A-Za-z0-9]\s*/, '-'
    str.gsub! /-+/, "-"
    self.slug = str.downcase 
  end

  def to_param
    self.slug
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?, :require_user, :require_same 
  # use this to expose the methods below to all views and controllers :require_user, :require_same
 
  def current_user
  # if there is a current user rtn that if not then rtn nil
  @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
 
  def logged_in?
  !!current_user # indicates whether a user is logged in (boolean)
  end
 
  def require_user
  if !logged_in?
  flash[:error] = "You need to be logged in to take that action"
  redirect_to root_path
  end
  end

  def require_same
  if current_user != @user
  flash[:error] = "You are not authorized to take that action."
  redirect_to root_path
  end
  end


  end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  require 'open-uri'
  require 'json'

  def index

  if logged_in?
  # get user from the database
  @user = current_user

  @interest_pre = (@user.interest1).gsub(/\s+/,'+') # add + symbol between each word if there are 2+ words to allow use in http searches - designates "or" in the article searches

  @free_pre = (@user.free_time).gsub(/\s+/,'+') # add + symbol between each word if there are 2+ words to allow use in http searches - designates "or" in the event searches

  @state_pre = @user.state.gsub(/\s+/,'_')
  @city_pre = @user.city.gsub(/\s+/,'_')

  @limit = (Date.today).days_ago(7)
  @begin_time = (@limit.to_s).gsub('-','')

  @nytimes_data = data_retrieve("http://api.nytimes.com/svc/search/v2/articlesearch.json?&q=" + @interest_pre + "&begin_date=" + @begin_time + "&sort=newest&api-key=bd2d3da37f58e2247ab30155400fc222:3:67128716")
  @weather_rpt = data_retrieve("http://api.wunderground.com/api/cfffe9ffeb7b662e/conditions/q/" + @state_pre + "/" + @city_pre + ".json")

  @meetup_data = data_retrieve("https://api.meetup.com/2/open_events?&sign=true&photo-host=public&zip=" + current_user.zipcode + "&text=" + @interest_pre + "&page=20&key=6874237675483c4f5e12f416939655a")
  @nytimes_top = data_retrieve("http://api.nytimes.com/svc/topstories/v1/home.json?api-key=799bb4a946ced430d7d8611ca957387b:8:67128716")
  @nytimes_events = data_retrieve("http://api.nytimes.com/svc/events/v2/listings.json?&query=" + @free_pre + "&limit=20&api-key=3484b827fcc7f7a5962abbf4b36fdfc4:19:67128716")


  # determine how many results were returned and rescue if there is an error
  @checker = {"Error Condition Alpha" => "There is an error in the response. Please try again."}  # error text
  @test_nytimes_data = @nytimes_data["response"].nil? rescue true
    if @test_nytimes_data
      @nytimes_data = @checker
      unless @test_nytimes_data
    @nytimes_data
    end
  end

  @weather_test = @weather_rpt['current_observation']['temp_f'].nil? rescue true
    if @weather_test
      @weather_rpt = @checker
      unless @weather_test
      @weather_rpt
    end
  end

  @test_meetup = @meetup_data.nil? rescue true
    if @test_meetup
      @meetup_data = @checker
      unless @test_meetup
    @meetup_data
    end
  end

  @test_nytimes_top = @nytimes_top.nil? rescue true
    if @test_nytimes_top
      @nytimes_top = @checker
      unless @test_nytimes_top
    @nytimes_top
    end
  end

  @test_nytimes_events = @nytimes_events.nil? rescue true
    if @test_nytimes_events
      @nytimes_events = @checker
      unless @test_nytimes_events
    @nytimes_data
    end
  end

else
  render 'index'

end

end

  # assign json array info to variables
  def data_retrieve(url_string)
    url = url_string  # open url

    begin
      data_read =open(url).read   # read the url
    rescue SocketError => e
      return {}
    end

    @data_result = JSON.parse(data_read)  # parse JSON received from the api

    return @data_result #return parsed JSON data to an instance variable

  end

  # end of class

# to do - pagination of results, improve formatting

  end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
def new
 # displays the login form
 
end
 
def create
user = User.find_by(username: params[:username])
if user && user.authenticate(params[:password])
session[:user_id] = user.id # save user_id and not an object
flash[:notice] = "You've logged in successfully. Welcome."
redirect_to root_path
else
flash[:error] = "Your username or e-mail is incorrect"
redirect_to register_path 
 end
end
 
 
def destroy
session[:user_id] = nil
flash[:notice] = "You have logged out"
redirect_to root_path 
 
end
 
 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :set_user, only: [:show, :edit, :update] #create slug
before_action :require_same, only: [:edit, :update] # only allow same user to edit and update their profile


def new
  @user = User.new
end
 
def create
  @user = User.new(user_params)
 
  if @user.save
  flash[:notice] = "Your user information has been saved. Welcome to Treble!"
  session[:user_id] = @user.id
  # now automatically log user into the site after their registration
  redirect_to root_path
  else
  render :new
  end
end
 

def edit
  # @user = User.find(params[:id])
end

def show
  # @user = User.find(params[:id])
end

 
def update
  if @user.update(user_params)
  flash[:notice] = "Your profile has been updated." 
  redirect_to user_path(@user)
  else
  render :update
  end
end
 

def user_params # allow whitelist through
  params.require(:user).permit(:username, :password, :city, :state, :zipcode, :interest1, :free_time)
end
 
def set_user
  @user = User.find_by(slug: params[:id])
end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/_articles.html.erb
 <div class='row'>

  <div class='span0 well text-center'>

 <% if interest.has_value?(@checker) %>
    <p class="intro_text">No articles meet your criteria<p>
      <% else %>


<table id="locations" class ="table1" cellspacing="0" width="75%">
  <thead>
    <tr>
    <th>Date</th>
    <th>Articles based on your interest</th>
  </tr>
  </thead>

<body>
  <tr>
     <% interest["response"]["docs"].each do |article| %>
    <td><%= article["pub_date"].to(9) %></td>

    <td><%= link_to (sanitize article["headline"]["main"]), article["web_url"], target: "_blank" %> </td>
      </tr>
    <% end %>


  </body>
</table>

<% end %>

</div>
</div>

app/views/home/_events.html.erb
<div class='row'>

  <div class='span0 well text-center'>

 <% if freetime.has_key?("Error Condition Alpha") %>
    <p class="intro_text">No events meet your criteria<p>
      <% else %>


<table id="locations" class ="table table-striped" cellspacing="0" width="100%">
  <thead>
  <tr>
    <th>"Event" </th>
    <th>Description</th>

  </tr>
  </thead>

<body>
  <tr>
      <% freetime["results"].each do |event| %>

           <td><%= link_to event["event_name"], event["event_detail_url"], target: "_blank" %></td>

            <td><%= sanitize event["web_description"] %></td>
     </tr>


    <% end %>
  </body>
</table>

<% end %>

app/views/home/_networking.html.erb
 <div class='row'>

  <div class='span0 well text-center'>

 <% if meetups.has_key?("Error Condition Alpha") %>
    <p class="intro_text">No meetups meet your criteria<p>
      <% else %>


<p>Meetup events based on your interest</p>
<table cellspacing="0" width="85%" class="table table-striped">
  <thead>

  <tr>
    <th>Meetup Group Name</th>
    <th>Event Name</th>
    <th>Status</th>
  </tr>
  </thead>

<body>
  <tr>
      <% meetups["results"].each do |meetup| %>

          <td><%= meetup["group"]["name"] %></td>

           <td><%= link_to meetup["name"], meetup["event_url"], target: "_blank" %></td>
           <td><%= meetup["status"] %></td>
  </tr>

      <% end %>

  </body>
</table>

<% end %>

app/views/home/_top_stories.html.erb
<div class='row'>
<div class="center-block">
  <div class='span0 well'>

    <% if stories.has_key?("Error Condition Alpha") %>
    <p class="intro_text">There are no top stories at this time.<p>
      <% else %>


<table id="locations" class ="table1" cellspacing="0" width="75%">
  <thead>
  <tr>

    <th>Today's Top Stories</th>
  </tr>
  </thead>

<body>
  <tr>
    <% stories["results"].each do |result| %>


      <td><%= link_to result["title"], result["url"], target: "_blank" %></td>
      </tr>

    <% end %>


  </body>
</table>

<% end %>
</div>
</div>
</div>

app/views/home/events.html.erb
<table id="locations" class ="table1" cellspacing="0" width="100%">
  <thead>
  <tr>
    <th><%= "Events based on your interest - " + User.free_time %></th>
    <th>Description</th>
    <th>Free?</th>
  </tr>
  </thead>

<body>
  <tr>
      <% @events_url.each do |url| %>
        <% @events_name.each do |name| %>
           <td><%= link_to url, name, target: "_blank" %></td>
            <% @events_desc.each do |description| %>
            <td><%= description %></td>
            <% @events_free.each do |free| %>
            <td><%= free %></td>
      </tr>
      <% end %>
    <% end %>
    <% end %>
    <% end %>
  </body>
</table>

app/views/home/home.html.erb
</div class='top_space'>
<div class='main_space' class='jumbotron'>
  <h1>Welcome to Treble!</h1>
</p>
<p><a 
  </div>
  <div class='bottom_space'>

app/views/home/index.html.erb
<% if !logged_in? %>

<div class="top_space"></div>



<div class='jumbotron'>
  <h1>Welcome to Treble!</h1>
 </div>
 <h3 class="intro_text">Treble is a way to quickly view top stories, news on your interests and see relevant local events.</h3>
 <h3 class="intro_text">Try it now!</h3>

<br>
<div class="row" id="center">
  <%= button_to "Sign up if you're new", register_path, :method => "get", class: "button_link1" %>
  <br>
  <%= button_to "Registered? Sign in", login_path, :method => "get", class: "button_link2" %>
</div>


  <div class='bottom_space'></div>

    <% else %>

<span>

  <div class="row">
  <div class='well'>
  <h2 class="intro_text"><%= link_to Treble, root_path %></h2>
  <br>
  <% if @weather_rpt.has_key?("Error Condition Alpha") %>
    <p class="intro_text">Sorry, there is no weather information at this time</p>
    <% else %>
<h4 class="intro_text">The weather at <%= current_user.city %><%= ", " %><%= current_user.state %> is currently <%= @weather_rpt['current_observation']['temp_f'] %> degrees F.</h4>
<br>
<p class="intro_text">Your interest is <%= @user.interest1  %>, and you like <%= @user.free_time %> in your free time.</p>
<% end %>
</div>
</div>
<br>

<div class="intro_text">
<div class="row" >
 <div role='tabpanel'>
  <ul class='nav nav-tabs nav-justified'>
    <li class='<%= 'active' if params[:tab].nil? %>'>
   <%= link_to "Top Stories", tab: nil %><span class="badge"><%= (@nytimes_top["results"]).length %> </li>

    <li class='<%= 'active' if params[:tab] == 'interests' %>'>
    <%= link_to "News on your interests", tab: 'interests' %><span class="badge"><%= (@nytimes_data["response"]["meta"]["hits"]).to_i %></li>

    <li class='<%= 'active' if params[:tab] == 'meetup' %>'>
    <%= link_to "Meetup Networking Opportunities", tab: 'meetup' %><span class="badge"><%= @meetup_data["results"].length %></span></li>

    <li class='<%= 'active' if params[:tab] == 'freetime' %>'>
    <%= link_to "Events for your free time", tab: 'freetime' %><span class="badge"><%= @nytimes_events["results"].length %> </span></li>

  </ul>

  <% if params[:tab].nil? %>
  <%= render 'top_stories', stories: @nytimes_top %>

  <% elsif params[:tab] == 'interests' %>
  <%= render 'home/articles', interest: @nytimes_data  %>

  <% elsif params[:tab] == 'meetup' %>
  <%= render 'networking', meetups: @meetup_data %>

  <% elsif params[:tab] == 'freetime' %>
  <%= render 'events', freetime: @nytimes_events %>

  <% end %>

</div>
</div>

</div>


  <% end %>

app/views/home/networking.html.erb
<table id="locations" class ="table1" cellspacing="0" width="100%">
  <thead>
    <% if @meetup_flag == 0 %>
    <p>No meetups meet your criteria<p>
      <% else %>
  <tr>
    <th><%= "Meetup events based on your interest -" + User.interest1 %></th>
    <th>Meetup Group Name</th>
    <th>Description</th>
    <th>Status</th>
  </tr>
  </thead>

<body>
  <tr>
      <% @meetup_grpname.each do |name| %>
        <td> <%= name %></td>
        <% @meetup_url.each do |url| %>
        <% @meetup_desc.each do |description| %>
           <td><%= link_to url, description, target: "_blank" %></td>
            <% @meetup_status.each do |status| %>
            <td><%= status %></td>
        </tr>
      <% end %>
    <% end %>
    <% end %>
    <% end %>
  </body>
</table>
<% end %>

app/views/home/top_stories.html.erb
<% if @top_flag == 0 %>
    <p>No articles meet your criteria<p>
      <% else %>


<table id="locations" class ="table1" cellspacing="0" width="100%">
  <thead>
  <tr>
    <th>Date</th>
    <th>Top Stories</th>
  </tr>
  </thead>

<body>
  <tr>
    <% @top_stories.each do |stories| %>
      <%= stories["published_date"].each do |date| %>
        <td><%= date %></td>
      <% stories["url"].each do |url| %>
      <% stories["title"].each do |title| %>
      <td><%= link_to url, title, target: "_blank" %></td>
      </tr>
    <% end %>
    <% end %>
    <% end %>
  </body>
</table>
<% end %>

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
<div class="row">
   <div class="alert alert-error span8">


<h5> There were some errors </h5>
<ul>
<% obj.errors.full_messages.each do |msg| %>
<li> <%= msg %>  </li>
<% end %>
</ul>
</div>
</div>
<% end %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<% if logged_in? %>
<div class="pull-right">
<div class='btn-group nav_item'>

                <%= link_to('#', class: 'btn btn-primary dropdown-toggle', 'data-toggle' => 'dropdown') do %>
<%= current_user.username %>  <span class='caret'></span> <% end %>
 
<ul class='dropdown-menu'>
    <li>
    <%= link_to edit_user_path(current_user) do %> <i class="icon-pencil"></i>Edit Profile<% end %>
    <%= link_to user_path(current_user) do %> <i class="icon icon-home"></i>View Profile<% end %>
    <%= link_to logout_path do %> <i class="icon icon-user"> </i>Logout<% end %>
    </li>
</ul> 
</div>          
</div>
   <% end %>            

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Treble</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
      <div class="navbar">
        <div class="navbar-inner">
          <div class="container">
            <% if logged_in? %>
            <%= render 'layouts/navigation' %>
            <% end %>
          </div>
        </div>
      </div>
    </header>
<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
 <div class="well">
<%= form_for @user do |f| %>
<%= render 'layouts/errors', obj: @user %>


<div class="control-group">
<%= f.label :username %>
<%= f.text_field :username%>
</div>

<div class="control-group">
<%= f.label :password %>
<%= f.password_field :password %>
</div>


<br>
<p>Your Location</p>
<div class="control-group">
<%= f.label :city %>
<%= f.text_field :city %>
</div>

<div class="control-group">
<%= f.label :state %>
<%= f.select(:state) do %>
  <% [['AK', "Alaska"], ['AL', "Alabama"], ['AR', "Arkansas"], ['AZ', "Arizona"], ['CA', "California"], ['CO', "Colorado"], ['CT', "Connecticut"], ['DC', "District of Columbia"], ['DE', "Delaware"], ['FL', "Florida"], ['GA', "Georgia"], ['HI', "Hawaii"], ['IA', "Iowa"], ['ID', "Idaho"], ['IL', "Illinois"], ['IN', "Indiana"], ['KS', "Kansas"], ['KY', "Kentucky"], ['LA', "Louisiana"], ['MA', "Massachusetts"], ['MD', "Maryland"], ['ME', "Maine"], ['MI', "Michigan"], ['MN', "Minnesota"], ['MO', "Missouri"], ['MS', "Mississippi"], ['MT', "Montana"], ['NC', "North Carolina"], ['ND', "North Dakota"], ['NE', "Nebraska"], ['NH', "New Hampshire"], ['NJ', "New Jersey"], ['NM', "New Mexico"], ['NV', "Nevada"], ['NY', "New York"], ['OH', "Ohio"], ['OK', "Oklahoma"], ['OR', "Oregon"], ['PA', "Pennsylvania"], ['RI', "Rhode Island"], ['SC', "South Carolina"], ['SD', "South Dakota"], ['TN', "Tennessee"], ['TX', "Texas"], ['UT', "Utah"], ['VA', "Virginia"], ['VT', "Vermont"], ['WA', "Washington"], ['WI', "Wisconsin"], ['WV', "West Virginia"], ['WY', "Wyoming"]].each do |s| %>
<%= content_tag(:option, s.last, value: s.first)  %>
<% end %>
<% end %>
</div>

<div class="control-group">
<%= f.label :zipcode %>
<%= f.text_field :zipcode %>
</div>

<br>
<p>Your Interests</p>
<div class="control-group">
<%= f.label :interest1, 'Your main interest' %>
<%= f.text_field :interest1 %>
</div>

<div class="control-group">
<%= f.label :free_time %>
<%= f.text_field :free_time %>
</div>
<br>



<%= f.submit (@user.new_record? ? "Register" : "Update Profile"), class: "btn btn-success"  %>

<% end %>
</div>

app/views/users/edit.html.erb
<h3>Edit User</h3>
<%= render 'form' %>

app/views/users/new.html.erb
<h3>Register New User -  <%= link_to "Treble", root_path %></h3>
<%= render 'form' %>

app/views/users/show.html.erb
<h2><%= link_to Treble, root_path %>
<h3>View profile: <%= @user.username %></h3>
<div class='well'>
	<dl class='dl-horizontal'>
		<dt>Username:</dt>
		<dd><%= @user.username %></dd>
	</dl>
</div>